### PR TITLE
Issue 1: Fix project build issue.

### LINKED ISSUE #1: Code fails to build
**Problem description**
Currently, the source-code in this code fails to build properly, due to some of the last changes. 

Here's the temporary workaround: 

1. Modify gradle.build line 231: `jar.enabled = true`
2. Execute: `./gradlew :kafka-adapter:build`
3. Execute: `./gradlew :kafka-adapter:install`
4. Execute: `./gradlew :kafka-adapter:publishShadowPublicationToMavenLocal`
5. Execute: `./gradlew build`

**Problem location**
build.gradle

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Fix the build issue and fix a flaky test.
 
**Purpose of the change**  
Fix #1 

**What the code does**  
- Ensures the build uses the shadow jar generated to run samples.
- Fix a flaky junit test.
- Update dependencies of Pravega-client 0.8.1 and other jars.

**How to verify it**  
Has been verfied in Jenkins job

### CODE REVIEW

**Review by chennv4 — APPROVED** [review]
LGTM

File: kafka-adapter/src/test/java/io/pravega/adapters/kafka/client/consumer/PravegaKafkaConsumerTests.java [hunk 1]
```diff
@@ -289,7 +289,7 @@ public void listTopicsReturnsPartitionsByTopic() {
     public void listTopicsTimesOurWhenTimeoutIsTooLow() {
         try (Consumer<String, Object> consumer = new PravegaKafkaConsumer<>(prepareDummyConsumerConfig())) {
             Collection<String> topics = new ArrayList<>();
-            for (int i = 0; i < 100; i++) {
+            for (int i = 0; i < 1000; i++) {
```
Comment (derekm) [inline kafka-adapter/src/test/java/io/pravega/adapters/kafka/client/consumer/PravegaKafkaConsumerTests.java:292]: this change seems unrelated, not sure if it snuck in

Comment (derekm) [reply kafka-adapter/src/test/java/io/pravega/adapters/kafka/client/consumer/PravegaKafkaConsumerTests.java:292]: nevermind, I missed your PR comment explaining the flaky test!

**Review by shiveshr — APPROVED** [review]
